name: jr_case_boilerplate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.1.2
  dio: ^5.4.0
  shared_preferences: ^2.0.15
  image_picker: ^1.0.7
  dotted_border: ^2.1.0
  permission_handler: ^11.0.1
  provider: ^6.0.2
  flutter_screenutil: ^5.9.3
  easy_localization: ^3.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.1.0
  google_sign_in: ^6.1.0
  flutter_inner_shadow: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#000000"          # Shartflix arka plan (siyah)
  image: assets/images/logo.png   # Senin logon
  branding: assets/images/logo.png
  android: true
  ios: true
  web: false
  fullscreen: true


flutter_icons:
    android: true
    ios: true
    image_path: "assets/images/logo.png"
    adaptive_icon_background: "#000000" # arka plan rengi (siyah)
    adaptive_icon_foreground: "assets/images/logo.png"


flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/animations/login.json
    - assets/images/
    - assets/icons/

  fonts:
    - family: InstrumentSans
      fonts:
        - asset: assets/fonts/InstrumentSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/InstrumentSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/InstrumentSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/InstrumentSans-SemiBold.ttf
          weight: 600
