// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0WOmvyQNQ66VTR5D1BCIK7tv4lJ2bPSc',
    appId: '1:529858607756:android:fb27ebce618962a79059a9',
    messagingSenderId: '529858607756',
    projectId: 'shartflix-3ef68',
    storageBucket: 'shartflix-3ef68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6AIF8oLEnNKm1xGqELi3AUh5-jt-1vb4',
    appId: '1:529858607756:ios:5152aabb62baf2bc9059a9',
    messagingSenderId: '529858607756',
    projectId: 'shartflix-3ef68',
    storageBucket: 'shartflix-3ef68.firebasestorage.app',
    androidClientId: '529858607756-nefpiaj4p6mgfutt0c8qmsrcbbtkr5n5.apps.googleusercontent.com',
    iosClientId: '529858607756-nja2k3445h58udunocaq7su7k39ksemr.apps.googleusercontent.com',
    iosBundleId: 'com.nodelabsjrcase.jrCaseBoilerplate',
  );
}
